import type { Job } from '@/types/domain'

export const seedJobs: Array<Omit<Job, 'id' | 'createdAt' | 'updatedAt'>> = [
  {
    slug: 'frontend-engineer',
    title: 'Frontend Engineer',
    shortDescription: 'Build delightful, accessible UIs with React and TypeScript.',
    longDescription:
      'As a Frontend Engineer you will own a customer-facing web app end-to-end — architecture, state management, accessibility, performance, and testing. You collaborate closely with design and backend, and you write code that other engineers enjoy reading.',
    level: 'mid',
    competencies: ['React', 'TypeScript', 'Accessibility (a11y)', 'State management', 'Testing', 'Performance'],
    questionPack: [
      { id: 'fe-tech-typed-forms', category: 'technical', prompt: 'Walk me through how you would build a type-safe form with validation.', competency: 'TypeScript', order: 1 },
      { id: 'fe-tech-state-boundaries', category: 'technical', prompt: 'How do you decide between client state, server state, and URL state?', competency: 'State management', order: 2 },
      { id: 'fe-tech-a11y-audit', category: 'technical', prompt: 'How would you audit an existing page for accessibility issues, and what would you fix first?', competency: 'Accessibility (a11y)', order: 3 },
      { id: 'fe-tech-perf-tti', category: 'technical', prompt: "Time-to-interactive is too slow. Walk me through how you'd diagnose and improve it.", competency: 'Performance', order: 4 },
      { id: 'fe-tech-react-perf-bug', category: 'technical', prompt: 'Walk me through a React performance bug you fixed and how you isolated the cause.', competency: 'React', order: 5 },
      { id: 'fe-tech-test-strategy', category: 'technical', prompt: 'How do you decide what to unit test, integration test, and end-to-end test on the frontend?', competency: 'Testing', order: 6 },
      { id: 'fe-behav-designer-conflict', category: 'behavioral', prompt: 'Tell me about a time you disagreed with a designer — how did you resolve it?', competency: 'React', order: 7 },
      { id: 'fe-behav-ownership', category: 'behavioral', prompt: 'Describe a frontend project you owned end-to-end. What did you ship, and what did you learn?', competency: 'React', order: 8 },
    ],
  },
  {
    slug: 'backend-engineer',
    title: 'Backend Engineer',
    shortDescription: 'Design and ship reliable APIs and data systems at scale.',
    longDescription:
      'You own core services that power our product. You think about correctness, observability, and operational excellence. You are comfortable choosing between SQL and NoSQL, writing migrations without downtime, and defining clean API contracts.',
    level: 'senior',
    competencies: ['API design', 'Databases & SQL', 'Distributed systems', 'Observability', 'Security', 'Testing'],
    questionPack: [
      { id: 'be-sys-url-shortener', category: 'system-design', prompt: 'Design a URL shortener that handles 10k writes/sec.', competency: 'Distributed systems', order: 1 },
      { id: 'be-sys-rate-limit', category: 'system-design', prompt: 'Design a distributed rate limiter for a public API.', competency: 'Distributed systems', order: 2 },
      { id: 'be-tech-zero-downtime-mig', category: 'technical', prompt: 'How would you add a NOT NULL column to a 200M-row table without downtime?', competency: 'Databases & SQL', order: 3 },
      { id: 'be-tech-api-versioning', category: 'technical', prompt: 'How do you version a public REST API when you need to make a breaking change?', competency: 'API design', order: 4 },
      { id: 'be-tech-observability', category: 'technical', prompt: 'Walk me through how you would add observability to a service you just shipped.', competency: 'Observability', order: 5 },
      { id: 'be-tech-auth-design', category: 'technical', prompt: 'How would you design auth for a multi-tenant API — what are the key security decisions?', competency: 'Security', order: 6 },
      { id: 'be-tech-testing-strategy', category: 'technical', prompt: 'How do you test a service with external dependencies without slowing CI down to a crawl?', competency: 'Testing', order: 7 },
      { id: 'be-behav-incident', category: 'behavioral', prompt: 'Describe a production incident you led to resolution.', competency: 'Observability', order: 8 },
      { id: 'be-behav-tradeoff', category: 'behavioral', prompt: 'Tell me about a technical tradeoff you made under time pressure.', competency: 'API design', order: 9 },
    ],
  },
  {
    slug: 'product-manager',
    title: 'Product Manager',
    shortDescription: 'Drive product strategy and delivery for a B2B SaaS surface.',
    longDescription:
      'You define the roadmap, talk to customers weekly, write crisp specs, and partner with engineering and design from discovery to launch. You balance vision with rigor: metrics, experiments, and hard prioritization calls.',
    level: 'mid',
    competencies: ['Discovery', 'Prioritization', 'Roadmapping', 'Metrics & analytics', 'Stakeholder communication', 'Execution'],
    questionPack: [
      { id: 'pm-sit-feature-slip', category: 'situational', prompt: 'Your engineering lead says a committed feature will slip by 4 weeks. Walk me through what you do.', competency: 'Execution', order: 1 },
      { id: 'pm-sit-competing-asks', category: 'situational', prompt: 'Sales wants feature A, CS wants feature B, and engineering has capacity for one. How do you decide?', competency: 'Prioritization', order: 2 },
      { id: 'pm-sit-no-data', category: 'situational', prompt: 'You need to make a product decision but the data is ambiguous and the deadline is tomorrow. What do you do?', competency: 'Prioritization', order: 3 },
      { id: 'pm-behav-wrong-decision', category: 'behavioral', prompt: 'Tell me about a product decision you made that turned out to be wrong.', competency: 'Execution', order: 4 },
      { id: 'pm-behav-discovery', category: 'behavioral', prompt: 'Walk me through your last customer-discovery cycle. How did it shape what you built?', competency: 'Discovery', order: 5 },
      { id: 'pm-behav-stakeholder', category: 'behavioral', prompt: 'Tell me about a time you had to say no to a senior stakeholder. How did you handle it?', competency: 'Stakeholder communication', order: 6 },
      { id: 'pm-tech-ab-vs-ship', category: 'technical', prompt: 'How do you decide whether to A/B test a change vs. ship to 100%?', competency: 'Metrics & analytics', order: 7 },
      { id: 'pm-tech-north-star', category: 'technical', prompt: 'How do you pick a north-star metric for a new product surface?', competency: 'Roadmapping', order: 8 },
    ],
  },
  {
    slug: 'data-analyst',
    title: 'Data Analyst',
    shortDescription: 'Turn raw data into decisions that move the business.',
    longDescription:
      'As a Data Analyst you bridge data engineering and business stakeholders. You write production-quality SQL, design dashboards that get used, and translate ambiguous business questions into crisp hypotheses. You are comfortable presenting findings to non-technical audiences and pushing back on flawed metrics.',
    level: 'mid',
    competencies: ['SQL & data querying', 'Statistical analysis', 'Data visualization', 'Business acumen', 'Communication', 'Python / R'],
    questionPack: [
      { id: 'da-tech-funnel-drop', category: 'technical', prompt: 'Our conversion funnel dropped 12% last Monday. Walk me through how you would investigate this.', competency: 'SQL & data querying', order: 1 },
      { id: 'da-tech-sql-window', category: 'technical', prompt: 'Write a query that returns each user\'s first and last purchase date along with their total spend.', competency: 'SQL & data querying', order: 2 },
      { id: 'da-tech-ab-test', category: 'technical', prompt: 'You ran an A/B test. The treatment group shows a 5% lift in revenue but only 80% stat significance. What do you recommend?', competency: 'Statistical analysis', order: 3 },
      { id: 'da-tech-dashboard-design', category: 'technical', prompt: 'A PM asks for a retention dashboard. What questions do you ask before you build it, and what would it show?', competency: 'Data visualization', order: 4 },
      { id: 'da-tech-bad-metric', category: 'technical', prompt: 'You notice that the north-star metric a team is optimizing is gaming another metric you care about. What do you do?', competency: 'Business acumen', order: 5 },
      { id: 'da-tech-python-pipeline', category: 'technical', prompt: 'Walk me through how you would build a repeatable data pipeline from raw API data to a clean analytics table.', competency: 'Python / R', order: 6 },
      { id: 'da-behav-insight', category: 'behavioral', prompt: 'Tell me about an analysis you ran that changed a business decision.', competency: 'Communication', order: 7 },
      { id: 'da-behav-stakeholder-pushback', category: 'behavioral', prompt: 'Describe a time a stakeholder disagreed with your analysis. How did you handle it?', competency: 'Communication', order: 8 },
    ],
  },
  {
    slug: 'designer',
    title: 'Product Designer',
    shortDescription: 'Shape the end-to-end user experience for a fast-moving B2B product.',
    longDescription:
      'As a Product Designer you own the full design lifecycle — from exploratory research to pixel-perfect handoffs. You work directly with PMs and engineers, hold the quality bar on our design system, and champion user needs in every sprint.',
    level: 'mid',
    competencies: ['Visual design', 'User research', 'Interaction design', 'Prototyping', 'Design systems', 'Collaboration'],
    questionPack: [
      { id: 'ds-tech-redesign-process', category: 'technical', prompt: 'Walk me through how you would redesign a checkout flow that has a 60% abandonment rate.', competency: 'Interaction design', order: 1 },
      { id: 'ds-tech-design-system', category: 'technical', prompt: 'How do you decide what belongs in a design system vs. a one-off component?', competency: 'Design systems', order: 2 },
      { id: 'ds-tech-research-methods', category: 'technical', prompt: 'You have two weeks to validate a new feature concept. What research methods do you use and why?', competency: 'User research', order: 3 },
      { id: 'ds-tech-accessibility', category: 'technical', prompt: 'How do you ensure your designs meet WCAG AA standards before handoff?', competency: 'Visual design', order: 4 },
      { id: 'ds-tech-prototype-fidelity', category: 'technical', prompt: 'When do you use a low-fidelity wireframe vs. a high-fidelity interactive prototype?', competency: 'Prototyping', order: 5 },
      { id: 'ds-sit-engineer-constraints', category: 'situational', prompt: 'An engineer tells you your design is not feasible in the current sprint. How do you respond?', competency: 'Collaboration', order: 6 },
      { id: 'ds-sit-conflicting-feedback', category: 'situational', prompt: 'The PM and the head of engineering give you conflicting feedback on a design. How do you resolve it?', competency: 'Collaboration', order: 7 },
      { id: 'ds-behav-portfolio-impact', category: 'behavioral', prompt: 'Walk me through a design decision you made that had a measurable positive impact.', competency: 'Visual design', order: 8 },
    ],
  },
]
